import { z } from "zod";
import { ApiError, route } from "@/lib/api/errors";
import { requireReadGrant } from "@/lib/auth/context";
import { assertCan } from "@/lib/permissions";
import { requireFileInChat, resolveDownload } from "@/lib/services/files";
import { streamTelegramFile } from "@/lib/api/stream";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Small JPEG thumbnail generated by Telegram (documents with previews, photos, videos). */
export const GET = route<RouteContext<"/api/files/[fileId]/thumbnail">>(async (req, { params }) => {
  const { fileId } = await params;
  if (!z.string().uuid().safeParse(fileId).success) throw ApiError.notFound("File");
  const ctx = await requireReadGrant(req, fileId);
  assertCan(ctx.principal, "files.view");
  const file = await requireFileInChat(ctx.chat.id, fileId);
  if (!file.thumbnailFileId && file.telegramKind !== "photo") throw ApiError.notFound("Thumbnail");
  const { filePath, size } = await resolveDownload(file, "thumbnail");
  return streamTelegramFile(req, filePath, { fileName: "thumbnail.jpg", mimeType: "image/jpeg", disposition: "inline", size, cacheSeconds: 3600 });
});
